"""Add AuditLog model

Revision ID: 038fdf6a2a2d
Revises: 9b9c583f2bb4
Create Date: 2025-09-04 14:36:53.186030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038fdf6a2a2d'
down_revision: Union[str, Sequence[str], None] = '9b9c583f2bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
