"""Add InternalComponent and InternalScore models

Revision ID: 9b9c583f2bb4
Revises: e6958bb00a68
Create Date: 2025-09-04 14:36:01.820419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9c583f2bb4'
down_revision: Union[str, Sequence[str], None] = 'e6958bb00a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
