"""Add first_login, department to User and coordinator_id to ClassSection

Revision ID: e6958bb00a68
Revises: 002
Create Date: 2025-09-04 14:33:08.016294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6958bb00a68'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sections', sa.Column('coordinator_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_class_section_coordinator', 'class_sections', 'users', ['coordinator_id'], ['id'])
    op.add_column('users', sa.Column('first_login', sa.Boolean(), nullable=False, server_default='True'))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'first_login')
    op.drop_constraint('fk_class_section_coordinator', 'class_sections', type_='foreignkey')
    op.drop_column('class_sections', 'coordinator_id')
    # ### end Alembic commands ###
